const EVENT_CARD_DATA = [
    {
        id: 1,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 2,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 3,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 4,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 5,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 6,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
    {
        id: 7,
        imageUrl: '/img/gdg-cover.png',
        imageTitle: 'Cloud meetup image',
        title: 'A very long name for a next GDG meetup',
        description: 'Detailed description of the event',
        date: '10 June',
    },
];

export default EVENT_CARD_DATA;
