backend:
  name: github
  repo: gdg-minsk/gdg-minsk-website
  branch: new-layout

collections:
  - name: socialNetwork
    label: Social Network
    folder: data/social-network
    create: true
    identifier_field: type
    fields:
      - { name: type, label: Type, widget: "select", options: ["facebook", "twitter", "telegram", "youtube", "instagram", "vk", "other"]}
      - { name: url, label: URL, widget: "string" }